### ISSUE TITLE
Bug: When receiving a wifi connection, the open button does nothing

### ISSUE THREAD

**Issue by 103sbavert** [Martichou/rquickshare#130]
You should either replace the button with a "connect" button which uses the internal API to actually connect (might be hard to do since so many implementations exist) or just get rid of the "Open" button entirely (which does nothing ofc).

Version: 0.10.1
OS: Arch Linux
AUR Package: r-quick-share (non-bin)

**Comment by Martichou** [comment]
I'll check that! So it's sending wifi creds from Android to rquickshare right?

**Comment by 103sbavert** [comment]
Yes, that's right. And it shows the creds right in the app ,too.

**Comment by Martichou** [comment]
The "issue" is still present due to the fact that there's no easy fix for it as there's no distinction between text or link like that (at least I did not in the core_lib). So workaround: display toast and allow to copy the text, but the open button stays.

https://github.com/Martichou/rquickshare/commit/4798d78b7ae3d01a14c1ff61a4c68062f1566487
