### ISSUE TITLE
Can you compile for ARM device, aka raspberry pi?

### ISSUE THREAD

**Issue by joewashear007** [Martichou/rquickshare#169]
I want to run this on a raspberry pi zero so I can easily send photos to here:

I think it work well with this project: https://magpi.raspberrypi.com/articles/pi-zero-w-smart-usb-flash-drive

How hard would it be to add arm based builds? Thank you!

**Comment by Martichou** [comment]
The project has been made ARM64 compatible a little while ago (https://github.com/Martichou/rquickshare/issues/97).

But as of today, I can't provide ARM64 builds due to Github Actions not providing any Linux ARM64 machines. This is something I'm waiting for before being able to release RQuickShare for ARM64.

You can still compile it yourself in theory, but I'm unsure about Raspberry PI as it's ARM (not 64) and not sure you have Webkit2Gdk or something like that on it. It is also worth noting that RQuickShare require confirmation of the PIN code before accepting a transfer, so if you don't have a display/mouse on your PI, it's worthless.

**Comment by joewashear007** [comment]
Awesomer, thanks! I will look to see if I can compile it.  Would it be
possible to make something like this headless? I am experimenting and want
to see if I could "natively share" photos from my phone to my TV
storage/raspberry pi.
*Joseph Livecchi*

**Comment by Martichou** [comment]
If by headless you mean without UI and without the need to accept each request, I do not plan to do that currently. But that's something easily doable using for example the binary in the core_lib folder.

**Comment by reviczky** [comment]
> The project has been made ARM64 compatible a little while ago ([#97](https://github.com/Martichou/rquickshare/issues/97)).
> 
> But as of today, I can't provide ARM64 builds due to Github Actions not providing any Linux ARM64 machines. This is something I'm waiting for before being able to release RQuickShare for ARM64.
> 
> You can still compile it yourself in theory, but I'm unsure about Raspberry PI as it's ARM (not 64) and not sure you have Webkit2Gdk or something like that on it. It is also worth noting that RQuickShare require confirmation of the PIN code before accepting a transfer, so if you don't have a display/mouse on your PI, it's worthless.

The runners for arm64 are now available: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ and https://github.blog/changelog/2026-01-29-arm64-standard-runners-are-now-available-in-private-repositories/
