### ISSUE TITLE
Feature request: command-line argument for which files to share

### ISSUE THREAD

**Issue by rexendevar** [Martichou/rquickshare#244]
Hear me out here because I know this is a GUI program first and foremost. I do NOT intend to actually send files from the command line. I intend to make a context menu item for Nautilus that will tell it to send the selected item(s) via RQuickShare. For this I need a .desktop file with an exec line: `r-quick-share --files "list" "of" "files"` which I can put variables in

**Comment by Martichou** [comment]
Hey! As this is a free and open source project, I won't do this because I won't use it myself. I'm keen to work on things I'll use, but I don't have enough time for something I won't use..

However that is very possible, you can even do that without the GUI app at all by creating a custom version of the binary which is inside the core_lib folder.

I'm going to close this issue as it's not planned, but anyone can fork and do the binary like you asked :)
