### ISSUE TITLE
Blurry Text on High Res Screen

### ISSUE THREAD

**Issue by rk4500** [Martichou/rquickshare#75]
The app interface is very blurry on my display when the resolution is set to 3200x2000. 
When dropping the resolution down to 1920x1200 it seems to be of equal sharpness compared to the rest of the system UI
This is on high res:
![Screenshot from 2024-05-03 11-14-53cropped](https://github.com/Martichou/rquickshare/assets/87379158/ac8d8421-679f-4054-a21a-fce4a61fee2b)
This one is on low res:
![Screenshot from 2024-05-03 11-17-29](https://github.com/Martichou/rquickshare/assets/87379158/13c64a35-98bb-49d3-bc48-97441ea46e36)
(see the images in full screen to see the proper blurriness)

**Comment by Martichou** [comment]
That's weird, I can't reproduce locally. My screen is 3440 x 1440, Scale at 100% and everything is crystal clear.
Can you give me more info about the OS/Screen?
- OS
- Resolution (already have)
- Scale
- Fractional Scaling enabled?

**Comment by rk4500** [comment]
Damn wonder why that's happening then.
Sure, I'm on Ubuntu 23.10 and the display is set to 200% scale (so no fractional scaling).
Leme know if there's anything else I can do to help

**Comment by Martichou** [comment]
Could it be due to the scaling not being 100%? Did you try?

**Comment by RaduTek** [comment]
I can confirm that the issue is caused by fractional scaling. I am using KDE Plasma 6.1 running on Wayland. The app also seems to be running in Wayland (checked with xwininfo).

It would be a nice fix for laptop users, as most laptop displays require fractional scaling for text to be at a comfortable size. Due to the blurryness, some of the text in the app has poor contrast to the background and is harder to read (like the help text below the Visibility state).

Unfortunately, this looks like an upstream issue with the framework you're using (Tauri): [Incorrect DPI scaling on Wayland/Linux #5600](https://github.com/tauri-apps/tauri/issues/5600), so it's probably out of your scope to fix it.

Appreciations on the work you've done, your app is far more responsive than official implementations for Windows from the likes of Google and Samsung.

### App looking sharp at 100% scaling:
![Sharp App at 100% scaling](https://github.com/user-attachments/assets/6611aa9e-bb49-49b4-a8ca-054869667947)

### App looking blurry at 125% scaling:
![Blurry App at 125% scaling](https://github.com/user-attachments/assets/71f5136e-e2ea-4501-905a-e1892149a0ec)
