### ISSUE TITLE
feat: bluetooth medium support

### ISSUE THREAD

**Issue by NeroBlackstone** [Martichou/rquickshare#77]
Hello! Thank you so much for developing this software!
Currently it can only be used under WIFI. Is there a way to achieve Bluetooth transmission? I use a restricted Wi-Fi network so this feature is useful for me

**Comment by Martichou** [comment]
Hi, that's certainly possible. However my knowledge about BT/BT LE communication is currently somewhat limited. Also the BT chip inside my computer isn't recent enough to support/handle BLE advertisement so it's somewhat limited already.

Maybe that's something I'll tackle in the future or maybe someone else would be willing to work on it.

The current work is to make BLEA work so an Android device becomes visible without any workaround. But the transfer will still be processed through LAN.

I'll leave the issue open so if anyone is willing to work on it, feel free and I'd be happy to help.

**Comment by Martichou** [comment]
update: first step towards this https://github.com/Martichou/rquickshare/commit/2a58a53eb0c1b92d8e3dc370ca044261f01a9356. Now RQuickShare broadcast his presence over bluetooth when trying to send a file to an android device.

**Comment by mrghosti3** [comment]
Just adding myself into discussion. I would be interested in working on Bluetooth medium support. But I could only start looking into it next year as currently I have other things to work on. :sweat_smile:

**Comment by KraXen72** [comment]
Hello, I would be interested in having this feature. Thanks!

**Comment by MrRulf** [comment]
Hi, to add my 2 cents, bluetooth is the wrong technology for transmission. iirc the limit for transmission is 2Mbps. Wifi Direct should be used instead, if people want this feature. Also because that is what quickshare and airdrop actually use. I don't know about the new Wifi Awareness, that maybe should also be looked into if somebody wants to work on this.

But there are many better ways for transmission than bluetooth.
