### ISSUE TITLE
feat: create a no-GUI version

### ISSUE THREAD

**Issue by Martichou** [Martichou/rquickshare#78]
The goal is to create a system tray with a notification only app which would be distributed as a different version than the GUI one.

Both would coexist on the repo, but the no-GUI version would allow people not wanting to have another chromium app running on their computer to be "happy" (I guess?) :)

**Comment by liskin** [comment]
Also, the Debian package can no longer be installed on Debian testing/unstable, as it depends on libwebkit2gtk-4.0-37 which is no longer there (it's been replaced with libwebkit2gtk-4.1-0) and the Debian stable version of libwebkit2gtk-4.0-37 isn't co-installable due to conflicts.

A no-GUI version would presumably solve this. (And so would a Flatpak version. 🙂)

**Comment by Aryan-2607** [comment]
> Also, the Debian package can no longer be installed on Debian testing/unstable, as it depends on libwebkit2gtk-4.0-37 which is no longer there (it's been replaced with libwebkit2gtk-4.1-0) and the Debian stable version of libwebkit2gtk-4.0-37 isn't co-installable due to conflicts.
> 
> A no-GUI version would presumably solve this. (And so would a Flatpak version. 🙂)

from where can i find the .deb file,can u please tell me?

**Comment by Martichou** [comment]
@Aryan-2607 it is no yet available, it's a WIP.

**Comment by liskin** [comment]
> from where can i find the .deb file,can u please tell me?

The one I was referring to was https://github.com/Martichou/rquickshare/releases/download/v0.7.1/r-quick-share_0.7.1_amd64.deb specifically.

**Comment by Martichou** [comment]
Moved to https://github.com/users/Martichou/projects/1/views/1
